[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r api/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
